### ISSUE TITLE
Add the Travel page

### ISSUE THREAD

**Issue by Princesso** [oscafrica/osf-website#179]
Feature: We need to design the travel page.
Find the new design [here](https://www.figma.com/file/uGbiNNx3nZqONJ7qBKORkG/website-%26-stage?node-id=291-2)

Guidelines:

In the repository, find the 2023 sub-folder in src. Please do not change files that are not related to this feature except when updating configurations or fixing a bug.
In the components folder, find the 2023 sub-folder and create the components you will need for the travel page.
We use Tailwind CSS; kindly complete the designs with Tailwind only.
Import the components where needed in the pages sub-folder of the 2023 folder.
If possible, write tests; however, this should not hinder you from contributing as the team regularly updates tests.
Special Note: Take note of mobile designs. We prefer a mobile-first approach.

If you have any questions, ask @BolajiAyodeji or @Princesso

Thank you

**Comment by CatherineKiiru** [comment]
Hi @Princesso, I'd like to work on this issue, please assign it to me

**Comment by Princesso** [comment]
Hi @CatherineKiiru, thank you. It is already assigned to you.

**Comment by Princesso** [comment]
Hi @CatherineKiiru , good day. Could you kindly update this issue with its actual state as of today? Thanks.

**Comment by CatherineKiiru** [comment]
Hi @Princesso, I have pushed what I've managed to work on so far, I've ran into dependency issues and the project keeps freezing my laptop. The only remaining section is implementing the Navbar and footer section.

**Comment by Princesso** [comment]
@CatherineKiiru please can you put a link to the PR?

**Comment by CatherineKiiru** [comment]
Hi @Princesso the pull request button is disabled and even after filling the PR template, I could not submit it.

**Comment by CatherineKiiru** [comment]
> I'm reassigning this task @CatherineKiiru thanks for the willingness to contribute, however, at this moment, we need to move really fast and can't keep waiting.

I understand. I did try to complete it but my laptop kept freezing whenever I tried to code. I thought it was VScode or Chrome, but I switched between the Brave browser and Firefox, and still ran into the same issue. This was also not happening with other projects. Thank you for letting me attempt the project.

**Comment by Princesso** [comment]
@t-bello7 yes you can.

**Comment by BolajiAyodeji** [comment]
> > I'm reassigning this task @CatherineKiiru thanks for the willingness to contribute, however, at this moment, we need to move really fast and can't keep waiting.
> 
> I understand. I did try to complete it but my laptop kept freezing whenever I tried to code. I thought it was VScode or Chrome, but I switched between the Brave browser and Firefox, and still ran into the same issue. This was also not happening with other projects. Thank you for letting me attempt the project.

Hi @CatherineKiiru,

Sorry, you're experiencing this. Although I know we have a known issue of dependency conflicts for first-time setup, this is new that the entire project froze, and it might be from your end or something. But regardless, after this festival, the engineering team will do a cleanup of this codebase and do some framework migrations that will resolve all dependency issues.

Regarding the disabled pull request button, that's new too, perhaps you didn't entire a title/description yet (but since you said you filled out the PR template, I believe this is not the case), or it was a temporary bug from GitHub. But any contributor can create a PR from their fork, and I hope you have a better experience next time.

If this issue is taken already, I encourage you to pick another up if you still can and let's see if you can get the project running locally, or you could use Codespaces. Thank you for your contribution.

**Comment by CatherineKiiru** [comment]
> > > I'm reassigning this task @CatherineKiiru thanks for the willingness to contribute, however, at this moment, we need to move really fast and can't keep waiting.
> > 
> > 
> > I understand. I did try to complete it but my laptop kept freezing whenever I tried to code. I thought it was VScode or Chrome, but I switched between the Brave browser and Firefox, and still ran into the same issue. This was also not happening with other projects. Thank you for letting me attempt the project.
> 
> Hi @CatherineKiiru,
> 
> Sorry, you're experiencing this. Although I know we have a known issue of dependency conflicts for first-time setup, this is new that the entire project froze, and it might be from your end or something. But regardless, after this festival, the engineering team will do a cleanup of this codebase and possibly migrate to Nextjs 13, resolving all dependency issues.
> 
> Regarding the disabled pull request button, that's new too, perhaps you didn't enter a title/description yet (but since you said you filled out the PR template, I believe this is not the case), or it was a temporary bug from GitHub. But any contributor can create a PR from their fork, and I hope you have a better experience next time.
> 
> If this issue is taken already, I encourage you to pick another up if you still can and let's see if you can get the project running locally, or you could use Codespaces. Thank you for your contribution.

Thank you for responding and allowing me to contribute to more issues. I will definitely investigate the issues on my end. Goo day.

**Comment by t-bello7** [comment]
@CatherineKiiru  can I suggest using the yarn package manager?  My laptop also freezes at intervals while working on the project but I think is the low specification of my laptop or either the Ubuntu software. Since the yarn package manager is not the official package manager for the project I added it to the .gitignore file on the PR #190. I hope it's alright to make that change @BolajiAyodeji ?
